function exportResult(url, clientFilename, mimetype) {
    $.ajax({
        url: url,
        success: download.bind(true, mimetype, clientFilename)
    });
}

function openNewWindow(url) {
    window.open(url);
}

function hasOwnProperty(object, property) {
    return object.hasOwnProperty(property);
}

function removeProperty(object, property) {
    delete object.property;
    return null;
}

// Explicitly send pageview generated by URL-changing AJAX call to Google Analytics
// --------------------------------------------------------------------------------
function sendGooglePageView(url) {
    //console.log("ga: " + url);
    ga('set', 'page', url);
    ga('set', 'title', document.title);
    ga('send', 'pageview');
}

function getCurrentTimeMillis() {
    var d = new Date();
    return d.getTime();
}
